Basic model
===


In [20]:
import numpy as np
inputs = [[0,1,2,3]
        ,[1,0,2.5,3.4]
        ,[0,-1,2.5,3.2]
        # 4x3 input 
        # 4 parameters
        # 3 series
]
weights = [
    [0,1,2,3],
    [1.2,1.3,2.2,-3],
    [0.1,1.2,2,3.4],
]
bias = [0.5,2,1,0.7]

weights2 = [
    [0,-2,1.7],
    [-1.2,0.3,-1],
    [0.1,-2,3],
]
bias2 = [0.5,-0.2,1]

output = np.dot( inputs,np.array(weights).T)
print(output)
output = np.dot( output,np.array(weights2).T)
print(output)

[[14.   -3.3  15.4 ]
 [15.2  -3.5  16.66]
 [13.6  -5.4  14.68]]
[[ 32.78  -33.19   54.2  ]
 [ 35.322 -35.95   58.5  ]
 [ 35.756 -32.62   56.2  ]]


In [21]:
np.array(weights2).T

array([[ 0. , -1.2,  0.1],
       [-2. ,  0.3, -2. ],
       [ 1.7, -1. ,  3. ]])

In [22]:
np.array(weights2)

array([[ 0. , -2. ,  1.7],
       [-1.2,  0.3, -1. ],
       [ 0.1, -2. ,  3. ]])